name: Checking
on: 
  pull_request:
    branches: [ github-action ]
jobs:
  pr-style:
    name: pr-style
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[[A-Z]+-\d+\]\s.+' # Regex the title should match.
  code-style:
    name: code-style
    runs-on: ubuntu-latest
    steps:
      - name: install packages
        run: |
          sudo apt-get -y install build-essential texi2html cat
          
          # indent 2.2.11, the lastest version (2.2.12) make a different result
          sudo apt-get -y install wget
          wget https://ftp.gnu.org/gnu/indent/indent-2.2.11.tar.gz
          tar xf indent-2.2.11.tar.gz
          cd indent-2.2.11
          ./configure
          sudo make -j install
          cd ..

          # astyle
          sudo apt-get -y install astyle
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - id: stylecheck
        continue-on-error: true
        run: |
          for f in ${{ steps.files.outputs.added_modified }}; do
            ext=$(expr $f : ".*\(\..*\)")
            case $ext in
            .c|.h|.i)
              echo "C-files"
              indent -l120 -lc120 ${f}
            ;;
            .cpp|.hpp|.ipp)
              echo "CPP"
            ~/bin/astyle26 --style=gnu --mode=c --indent-namespaces --indent=spaces=2 -xT8 -xt4 --add-brackets --max-code-length=120 --align-pointer=name --indent-classes --pad-header --pad-first-paren-out ${f}
            ;;
            esac
          done 
          git diff | tee gitdiff
          test ! -s gitdiff # empty -> 0, not empty -> 1
      - id: get-comment-body
        if: ${{ steps.stylecheck.outcome == 'failure' }}
        run: |
          body=$(cat dgitdiff)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body
      - name: Create comment
        if: ${{ steps.stylecheck.outcome == 'failure' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }} 
	  body: test  #${{ steps.get-comment-body.outputs.body }}
  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - run: echo "cppcheck!"; -1;

