name: Checking
on: 
  pull_request:
    branches: [ github-action ]
jobs:
  pr-style:
    name: pr-style
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[[A-Z]+-\d+\]\s.+' # Regex the title should match.
  code-style:
    name: code-style
    runs-on: ubuntu-latest
    steps:
      - name: install packages
        run: |
          sudo apt-get -y install astyle
          sudo apt-get -y install indent=2.2.11
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for f in ${{ steps.files.outputs.added_modified }}; do
            ext=$(expr $f : ".*\(\..*\)")
            case $ext in
            .c|.h|.i)
              echo "C-files";
              indent -l120 -lc120 ${f}
            ;;
            .cpp|.hpp|.ipp)
              echo "CPP";
            ~/bin/astyle26 --style=gnu --mode=c --indent-namespaces --indent=spaces=2 -xT8 -xt4 --add-brackets --max-code-length=120 --align-pointer=name --indent-classes --pad-header --pad-first-paren-out ${f}
            ;;
            esac
          done 
          git diff | tee gitdiff;
          test ! -s gitdiff # empty -> 0, not empty -> 1
  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - run: echo "cppcheck!"; -1;

