name: Checking
on: 
  pull_request:
    branches: [ github-action ]
jobs:
  pr-style:
    name: pr-style
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[[A-Z]+-\d+\]\s.+' # Regex the title should match.
  code-style:
    name: code-style
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1  
      - run: |
          for f in ${{ steps.files.outputs.added_modified }}; do
            echo "Do something with this ${f}."
          done 
  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - run: echo "cppcheck!"; -1;
