name: Checking
on: 
  pull_request:
    branches: [ github-action ]
jobs:
  pr-style:
    name: pr-style
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[[A-Z]+-\d+\]\s.+' # Regex the title should match.
  code-style:
    name: code-style
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install astyle
      - id: files
        uses: jitterbit/get-changed-files@v1  
      - run: |
          for f in ${{ steps.files.outputs.added_modified }}; do
            astyle --style=gnu --mode=c --indent-namespaces --indent=spaces=2 -xT8 -xt4 --add-brackets --max-code-length=120 --align-pointer=name --indent-classes --pad-header --pad-first-paren-out ${f};
            diff ${f}.orig ${f};
          done 
  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - run: echo "cppcheck!"; -1;
